
export const GET_TODOS = 'GET_TODOS';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

export const POST_TODOS_SUCCESS = 'POST_TODOS_SUCCESS';
export const UPDATE_TODOS_SUCCESS = 'UPDATE_TODOS_SUCCESS';
export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS';
